### ISSUE TITLE
Fix Compile with .NET Native Toolchain

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/Macalifa#5]
This will prevent decompilation of the App and also increase performance and debugging.

**Comment by theweavrs** [comment]
This is now fixed. Compiling with .Net Native Toolchain works flawlessly.

**Comment by MattWhilden** [comment]
Hello! I work on the .NET Native compiler team. Any idea what was causing you a headache?

**Comment by theweavrs** [comment]
This was all I could find on the problem specific to `bass.dll`:
http://www.un4seen.com/forum/?topic=16665.msg120445#msg120445

But that didn't give me a clue on how to fix it. Apparently they fixed the bug, it must have been something in `bass.dll` probably the P/Invoke calls.

**Comment by MattWhilden** [comment]
Ah yes, we worked with them on that issue last month. Glad to hear it's worked out for you. Do feel free to let me know if you run into other issues with .NET Native.
